development:
  adapter: postgresql
  encoding: utf8
  database: onboarding_wisboo_development
  username: wisboo
  password: wisboo

test:
  adapter: postgresql
  encoding: utf8
  database: onboarding_wisboo_test
  username: wisboo
  password: wisboo

